### PR TITLE
refactor: declare structs concisely

### PR DESCRIPTION
**Pull request by buddisattva**

### CODE REVIEW

**Review by gongmusian — COMMENTED** [review]
{
      "@type": "Person",
      "name": "Sean",
      "image": [
        "https://example.com/photos/1x1/photo.jpg",
        "https://example.com/photos/4x3/photo.jpg",
        "https://example.com/photos/16x9/photo.jpg"
       ],
      "description": "Sean has a dick with 20 cm length and 5 cm width",
      "dick": {
        "@type": "Dick",
        "length": "20",
        "width": "5"
      }
    }

**Comment by buddisattva** [comment]
> ```
> {
>   "@type": "Person",
>   "name": "Sean",
>   "image": [
>     "https://example.com/photos/1x1/photo.jpg",
>     "https://example.com/photos/4x3/photo.jpg",
>     "https://example.com/photos/16x9/photo.jpg"
>    ],
>   "description": "Sean has a dick with 20 cm length and 5 cm width",
>   "dick": {
>     "@type": "Dick",
>     "length": "20",
>     "width": "5"
>   }
> }
> ```

thx

**Review by gongmusian — COMMENTED** [review]
We can design the meta data like google structure data.
https://developers.google.com/search/docs/data-types/product

**Comment by buddisattva** [comment]
> %.2f 是小數點後兩位嗎？
> 這部分也是存 “20.00” 嗎

是的。
另外目前資料沒有儲存，運算後僅供顯示用途。

**Review by gongmusian — APPROVED** [review]
OK!!!
Thank You~~~

**Pull request merged**
